//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.36366
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.PersonaServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://schemas.datacontract.org/2004/07/WCF_WS.Data")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CX {
            get {
                return this.CXField;
            }
            set {
                if ((object.ReferenceEquals(this.CXField, value) != true)) {
                    this.CXField = value;
                    this.RaisePropertyChanged("CX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CY {
            get {
                return this.CYField;
            }
            set {
                if ((object.ReferenceEquals(this.CYField, value) != true)) {
                    this.CYField = value;
                    this.RaisePropertyChanged("CY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PersonaServiceReference.IPersonaService")]
    public interface IPersonaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/GetPersona", ReplyAction="http://tempuri.org/IPersonaService/GetPersonaResponse")]
        WCF.PersonaServiceReference.Persona GetPersona(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/GetPersona", ReplyAction="http://tempuri.org/IPersonaService/GetPersonaResponse")]
        System.Threading.Tasks.Task<WCF.PersonaServiceReference.Persona> GetPersonaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/GetAllPersonas", ReplyAction="http://tempuri.org/IPersonaService/GetAllPersonasResponse")]
        WCF.PersonaServiceReference.Persona[] GetAllPersonas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/GetAllPersonas", ReplyAction="http://tempuri.org/IPersonaService/GetAllPersonasResponse")]
        System.Threading.Tasks.Task<WCF.PersonaServiceReference.Persona[]> GetAllPersonasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/CreatePersona", ReplyAction="http://tempuri.org/IPersonaService/CreatePersonaResponse")]
        bool CreatePersona(WCF.PersonaServiceReference.Persona p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/CreatePersona", ReplyAction="http://tempuri.org/IPersonaService/CreatePersonaResponse")]
        System.Threading.Tasks.Task<bool> CreatePersonaAsync(WCF.PersonaServiceReference.Persona p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/EditPersona", ReplyAction="http://tempuri.org/IPersonaService/EditPersonaResponse")]
        bool EditPersona(WCF.PersonaServiceReference.Persona p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/EditPersona", ReplyAction="http://tempuri.org/IPersonaService/EditPersonaResponse")]
        System.Threading.Tasks.Task<bool> EditPersonaAsync(WCF.PersonaServiceReference.Persona p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/DeletePersona", ReplyAction="http://tempuri.org/IPersonaService/DeletePersonaResponse")]
        bool DeletePersona(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/DeletePersona", ReplyAction="http://tempuri.org/IPersonaService/DeletePersonaResponse")]
        System.Threading.Tasks.Task<bool> DeletePersonaAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersonaServiceChannel : WCF.PersonaServiceReference.IPersonaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonaServiceClient : System.ServiceModel.ClientBase<WCF.PersonaServiceReference.IPersonaService>, WCF.PersonaServiceReference.IPersonaService {
        
        public PersonaServiceClient() {
        }
        
        public PersonaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCF.PersonaServiceReference.Persona GetPersona(int id) {
            return base.Channel.GetPersona(id);
        }
        
        public System.Threading.Tasks.Task<WCF.PersonaServiceReference.Persona> GetPersonaAsync(int id) {
            return base.Channel.GetPersonaAsync(id);
        }
        
        public WCF.PersonaServiceReference.Persona[] GetAllPersonas() {
            return base.Channel.GetAllPersonas();
        }
        
        public System.Threading.Tasks.Task<WCF.PersonaServiceReference.Persona[]> GetAllPersonasAsync() {
            return base.Channel.GetAllPersonasAsync();
        }
        
        public bool CreatePersona(WCF.PersonaServiceReference.Persona p) {
            return base.Channel.CreatePersona(p);
        }
        
        public System.Threading.Tasks.Task<bool> CreatePersonaAsync(WCF.PersonaServiceReference.Persona p) {
            return base.Channel.CreatePersonaAsync(p);
        }
        
        public bool EditPersona(WCF.PersonaServiceReference.Persona p) {
            return base.Channel.EditPersona(p);
        }
        
        public System.Threading.Tasks.Task<bool> EditPersonaAsync(WCF.PersonaServiceReference.Persona p) {
            return base.Channel.EditPersonaAsync(p);
        }
        
        public bool DeletePersona(int id) {
            return base.Channel.DeletePersona(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePersonaAsync(int id) {
            return base.Channel.DeletePersonaAsync(id);
        }
    }
}
